site_name: Jesse's Doco
site_url: https://doco.jpboyce.org
theme:
  name: material
  feature:
    - navigation.expanded
    - navigation.path
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - tags
  - search
  
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jpboyce
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jpboyce/
  consent:
    title: Cookie consent
    description: >-
      This website uses cookies to ensure you get the best experience on our website.          